services:
  bot:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - TELEGRAM_TOKEN
      - TEST_TELEGRAM_TOKEN
      - FEEDBACK_CHANNEL_ID
      - MONGO_URL
      - REPO_URL
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 8000:8000
