PROD = "prod"
DEV = "dev"

REFRESH_TIME_HOURS = 24
TIMEOUT_SECONDS = 5

(
    AWAIT_SELECTION,
    AWAIT_CUSTOM_INPUT,
    AWAIT_FEEDBACK,
    INPUT_COLLEGE,
    INPUT_DEPARTMENT,
    INPUT_COURSE_NUM,
    INPUT_SECTION,
    SUBMIT,
    CANCEL,
) = map(chr, range(9))

(
    COLLEGE,
    DEPARTMENT,
    COURSE_NUM,
    SECTION,
    IS_SUBSCRIBED,
    LAST_SUBSCRIBED,
    LAST_SUBSCRIPTION,
    SUBSCRIPTION_MSG_ID,
    PROMPT_MSG_ID,
    INVALID_MSG_ID,
) = map(chr, range(10))

FORM_FIELDS = {COLLEGE, DEPARTMENT, COURSE_NUM, SECTION}
