PROD = "prod"
DEV = "dev"

REFRESH_TIME_HOURS = 24
TIMEOUT_SECONDS = 5

(
    AWAIT_SELECTION,
    AWAIT_CUSTOM_INPUT,
    AWAIT_INPUT_USERNAME,
    AWAIT_INPUT_PASSWORD,
    AWAIT_FEEDBACK,
    INPUT_COLLEGE,
    INPUT_DEPARTMENT,
    INPUT_COURSE_NUM,
    INPUT_SECTION,
    INPUT_USERNAME,
    INPUT_PASSWORD,
    SUBMIT,
    PROCEED,
    CANCEL,
) = map(chr, range(14))

(
    COLLEGE,
    DEPARTMENT,
    COURSE_NUM,
    SECTION,
    USERNAME,
    PASSWORD,
    IS_SUBSCRIBED,
    LAST_SUBSCRIBED,
    LAST_SUBSCRIPTION,
    SUBSCRIPTION_MSG_ID,
    PROMPT_MSG_ID,
    INVALID_MSG_ID,
    CRED_MSG_ID,
) = map(chr, range(13))

FORM_FIELDS = {COLLEGE, DEPARTMENT, COURSE_NUM, SECTION}
CRED_FIELDS = {USERNAME, PASSWORD}
